# <font color='purple'> **100 NUMPY EXERCISES** </font>

<font color = 'gray'> *Author: Dania Garcia | 9° IDGS* </font>

In [2]:
# 1. Importar paquete de Numpy
import numpy as np

In [3]:
# 2.1 Conocer versión del paquete
print(np.__version__)

1.26.3


In [13]:
# 2.2 Conocer la configuración
# # 'stdout' -> lo que significa que la información se imprimirá en la salida estándar (normalmente la consola o terminal).
np.show_config

<function numpy.__config__.show(mode='stdout')>

In [6]:
# 3. Crear arreglo tamaño 10 con ceros
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# 4. Obtener documentación con salida en consola. 
# Usar help()
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [15]:
# 5. Hacer que el arreglo del ejercicio 3, el quinto valor sea 1
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
# 6. Crear un array con valores de 10 a 49
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [22]:
# 7. Hacer que el primer elemento sea el último
Z = np.arange(50)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [32]:
# 8. Crear una matriz de 3x3 de 0 a 8
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
# 9. Encontrar los índices que sean distintos a 0 de [1,2,0,0,4,0]
list = [1,2,0,0,4,0]
nz = np.array(list)
nz

array([1, 2, 0, 0, 4, 0])

In [38]:
nz_indices = np.nonzero(nz)
nz_indices

(array([0, 1, 4], dtype=int64),)

In [39]:
# 10. Crear una matriz 3x3, donde se haga una diagonal con los valores 1, y los demás 0
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# 11. Crear un array 3x3x3, con valore ramdom
z = np.random.random((3,3,3))
z

array([[[0.47094787, 0.50052978, 0.12784304],
        [0.80929327, 0.37496596, 0.22191741],
        [0.95937577, 0.59731364, 0.79275145]],

       [[0.5352274 , 0.18401084, 0.30195513],
        [0.66850553, 0.02857294, 0.50745207],
        [0.5999396 , 0.75599135, 0.38383778]],

       [[0.325648  , 0.91102252, 0.39065356],
        [0.12488378, 0.40777273, 0.30467937],
        [0.08020944, 0.23095711, 0.04819253]]])

In [41]:
# 12.1 Crear un array 10x10 con valores random
z = np.random.random((10,10))
z

array([[0.33326845, 0.14762897, 0.57446378, 0.24698238, 0.79554277,
        0.27163661, 0.51430122, 0.85363651, 0.8063002 , 0.14136332],
       [0.13320266, 0.02634857, 0.40761292, 0.53652191, 0.52010262,
        0.10693905, 0.78880148, 0.56565583, 0.98015484, 0.90174415],
       [0.49427208, 0.39450744, 0.13110049, 0.52439308, 0.0639171 ,
        0.88871241, 0.04171208, 0.48127131, 0.28483996, 0.09805838],
       [0.79008168, 0.84024483, 0.65368072, 0.11309008, 0.62540935,
        0.06780578, 0.20595332, 0.36324379, 0.05808351, 0.0612546 ],
       [0.51071802, 0.0902673 , 0.04623361, 0.86063079, 0.3536545 ,
        0.25624377, 0.44334331, 0.4189069 , 0.19394975, 0.22591767],
       [0.61369966, 0.30223577, 0.6952809 , 0.05939026, 0.20853989,
        0.6256457 , 0.92139165, 0.5819683 , 0.73621308, 0.1279503 ],
       [0.44273131, 0.03421683, 0.87325245, 0.78659703, 0.15323609,
        0.84060837, 0.28789453, 0.01524901, 0.0906923 , 0.92036863],
       [0.33774084, 0.14589551, 0.3641136

In [45]:
#12.2 Encontrar las valores máximos y mínimos
Zmin, Zmax = z.min(), z.max()
Zmin

0.01365740486348932

In [46]:
Zmax

0.9969700754861458

In [51]:
# 13.1 Crear un vector de 30 con valores random
low = 1
high = 100
z = np.random.randint(low,high,size=30)
z

array([74, 14, 18, 57, 37, 61, 53, 19, 64, 23, 67, 96, 89, 46, 97, 99, 64,
       94, 15, 32, 27,  4, 17, 34, 74, 16, 27, 78, 95, 58])

In [52]:
# 13.2 Encontrar el promedio
z_promedio = np.mean(z)
z_promedio

51.63333333333333

In [53]:
# 14. Crear un array 2d con 1 en el borde, y 0  adentro
z = np.ones((10,10))
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [56]:
z[1:-1,1:-1] = 0
#1:-1: Este slicing indica que estamos seleccionando todas las filas y columnas del array z, excepto la primera y la última fila
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [62]:
# 15. ¿Qué resultado se obtiene de la siguuiente expresión?
0 * np.nan
# Cualquier operación con un valor NaN también produce un resultado NaN.


nan

In [58]:
np.nan == np.nan


False

In [59]:
np.inf > np.nan


False

In [63]:
np.nan - np.nan
#cualquier operación con un valor NaN también produce un resultado NaN.

nan

In [64]:
0.3 == 3 * 0.1
# la forma en que se almacenan los números de punto flotante en la computadora y cómo se realizan  
# las operaciones aritméticas con ellos, la comparación puede no dar el resultado esperado.

False