# <font color='purple'> **100 NUMPY EXERCISES** </font>

<font color = 'gray'> *Author: Dania Garcia | 9° IDGS* </font>

In [2]:
# 1. Importar paquete de Numpy
import numpy as np

In [3]:
# 2.1 Conocer versión del paquete
print(np.__version__)

1.26.3


In [13]:
# 2.2 Conocer la configuración
# # 'stdout' -> lo que significa que la información se imprimirá en la salida estándar (normalmente la consola o terminal).
np.show_config

<function numpy.__config__.show(mode='stdout')>

In [6]:
# 3. Crear arreglo tamaño 10 con ceros
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# 4. Obtener documentación con salida en consola. 
# Usar help()
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [15]:
# 5. Hacer que el arreglo del ejercicio 3, el quinto valor sea 1
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
# 6. Crear un array con valores de 10 a 49
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [22]:
# 7. Hacer que el primer elemento sea el último
Z = np.arange(50)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [32]:
# 8. Crear una matriz de 3x3 de 0 a 8
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
# 9. Encontrar los índices que sean distintos a 0 de [1,2,0,0,4,0]
list = [1,2,0,0,4,0]
nz = np.array(list)
nz

array([1, 2, 0, 0, 4, 0])

In [38]:
nz_indices = np.nonzero(nz)
nz_indices

(array([0, 1, 4], dtype=int64),)

In [39]:
# 10. Crear una matriz 3x3, donde se haga una diagonal con los valores 1, y los demás 0
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# 11. Crear un array 3x3x3, con valore ramdom
z = np.random.random((3,3,3))
z

array([[[0.47094787, 0.50052978, 0.12784304],
        [0.80929327, 0.37496596, 0.22191741],
        [0.95937577, 0.59731364, 0.79275145]],

       [[0.5352274 , 0.18401084, 0.30195513],
        [0.66850553, 0.02857294, 0.50745207],
        [0.5999396 , 0.75599135, 0.38383778]],

       [[0.325648  , 0.91102252, 0.39065356],
        [0.12488378, 0.40777273, 0.30467937],
        [0.08020944, 0.23095711, 0.04819253]]])

In [41]:
# 12.1 Crear un array 10x10 con valores random
z = np.random.random((10,10))
z

array([[0.33326845, 0.14762897, 0.57446378, 0.24698238, 0.79554277,
        0.27163661, 0.51430122, 0.85363651, 0.8063002 , 0.14136332],
       [0.13320266, 0.02634857, 0.40761292, 0.53652191, 0.52010262,
        0.10693905, 0.78880148, 0.56565583, 0.98015484, 0.90174415],
       [0.49427208, 0.39450744, 0.13110049, 0.52439308, 0.0639171 ,
        0.88871241, 0.04171208, 0.48127131, 0.28483996, 0.09805838],
       [0.79008168, 0.84024483, 0.65368072, 0.11309008, 0.62540935,
        0.06780578, 0.20595332, 0.36324379, 0.05808351, 0.0612546 ],
       [0.51071802, 0.0902673 , 0.04623361, 0.86063079, 0.3536545 ,
        0.25624377, 0.44334331, 0.4189069 , 0.19394975, 0.22591767],
       [0.61369966, 0.30223577, 0.6952809 , 0.05939026, 0.20853989,
        0.6256457 , 0.92139165, 0.5819683 , 0.73621308, 0.1279503 ],
       [0.44273131, 0.03421683, 0.87325245, 0.78659703, 0.15323609,
        0.84060837, 0.28789453, 0.01524901, 0.0906923 , 0.92036863],
       [0.33774084, 0.14589551, 0.3641136

In [45]:
#12.2 Encontrar las valores máximos y mínimos
Zmin, Zmax = z.min(), z.max()
Zmin

0.01365740486348932

In [46]:
Zmax

0.9969700754861458

In [51]:
# 13.1 Crear un vector de 30 con valores random
low = 1
high = 100
z = np.random.randint(low,high,size=30)
z

array([74, 14, 18, 57, 37, 61, 53, 19, 64, 23, 67, 96, 89, 46, 97, 99, 64,
       94, 15, 32, 27,  4, 17, 34, 74, 16, 27, 78, 95, 58])

In [52]:
# 13.2 Encontrar el promedio
z_promedio = np.mean(z)
z_promedio

51.63333333333333

In [53]:
# 14. Crear un array 2d con 1 en el borde, y 0  adentro
z = np.ones((10,10))
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [56]:
z[1:-1,1:-1] = 0
#1:-1: Este slicing indica que estamos seleccionando todas las filas y columnas del array z, excepto la primera y la última fila
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [62]:
# 15. ¿Qué resultado se obtiene de la siguuiente expresión?
0 * np.nan
# Cualquier operación con un valor NaN también produce un resultado NaN.


nan

In [65]:
np.nan == np.nan
#Dos valores NaN no son considerados iguales. Esto es porque NaN representa un valor indeterminado o no definido, 
#y no tiene un sentido definido de igualdad

False

In [66]:
np.inf > np.nan
#Cualquier comparación con NaN (incluso con infinito) generalmente devuelve False.

False

In [63]:
np.nan - np.nan
#cualquier operación con un valor NaN también produce un resultado NaN.

nan

In [64]:
0.3 == 3 * 0.1
# la forma en que se almacenan los números de punto flotante en la computadora y cómo se realizan  
# las operaciones aritméticas con ellos, la comparación puede no dar el resultado esperado.

False

In [67]:
#16. Crea una matriz 5x5 con valores de 1-4 en la diagonal
Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
#np.arange(4): Esta función crea un array que contiene los números [0, 1, 2, 3].

#1+np.arange(4): Le sumamos 1 a cada elemento del array, obteniendo [1, 2, 3, 4].

#np.diag(1+np.arange(4), k=-1): Esta función crea una matriz diagonal con los elementos de [1, 2, 3, 4] 
#en su diagonal principal, desplazados una posición hacia abajo (k=-1).

In [69]:
#17. Crear una matriz de 8x8 e inicializarla con un patrón de tablero de ajedrez usando NumPy
tablero = np.zeros((8,8), dtype=int)
tablero

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [70]:
#Rellenar filas impares con unos
tablero[1::2, ::2] = 1
tablero

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [71]:
#Rellenar filas pares con unos
tablero[::2, 1::2] = 1
tablero

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [72]:
#18. Determinar los índices (x, y, z) del elemento 100 en un array de forma (6, 7, 8)
print(np.unravel_index(100,(6,7,8)))
#6 capas, 7 filas por cada capa, 8 columnas por cada fila

(1, 5, 4)


In [73]:
#19. Crear un tablero de ajedréz usando la función .tile
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [74]:
#np.tile(..., (4, 4)): Esta es la función np.tile() que toma dos argumentos: el patrón básico y una tupla que indica
#El primer argumento (np.array([[0,1],[1,0]])) es el patrón básico que queremos repetir.
#El segundo argumento (4, 4) indica que queremos repetir el patrón 4 veces tanto en el eje de las filas como en el eje de las columnas.

In [81]:
# 20. Normalizar una matriz aleatoria de 5x5 
# Hacer que todos los valores esten en el rango de [0,1]
z = np.random.random((5,5))
z

array([[0.18775848, 0.12781712, 0.57959282, 0.81331432, 0.70044032],
       [0.51258757, 0.526064  , 0.42036499, 0.02014312, 0.76945581],
       [0.66745958, 0.42842362, 0.46215324, 0.81040149, 0.13132288],
       [0.55169751, 0.63895553, 0.22707144, 0.06970215, 0.14024199],
       [0.53514576, 0.26662421, 0.0102684 , 0.290004  , 0.36724052]])

In [82]:
zmax, zmin = z.max(), z.min()
z = (z - zmin)/(zmax - zmin)
z

array([[0.22102108, 0.14637858, 0.70895624, 1.        , 0.85944266],
       [0.62551736, 0.64229901, 0.51067639, 0.01229658, 0.94538481],
       [0.81837309, 0.52071147, 0.56271357, 0.99637277, 0.15074415],
       [0.67421936, 0.78287818, 0.26997589, 0.07401041, 0.16185076],
       [0.65360815, 0.31922933, 0.        , 0.34834322, 0.44452267]])

In [88]:
# 21. Crear un tipo de dato personalizado que describa un color como cuatro bytes sin signo (R, G, B, A)
color_dtype = np.dtype([("r", np.uint8), 
                  ("g", np.uint8), 
                  ("b", np.uint8), 
                  ("a", np.uint8)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [89]:
colors = np.array([(255, 0, 0, 255),    # Rojo
                   (0, 255, 0, 255),    # Verde
                   (0, 0, 255, 255),    # Azul
                   (255, 255, 0, 255)   # Amarillo
], dtype=color_dtype)

colors

array([(255,   0,   0, 255), (  0, 255,   0, 255), (  0,   0, 255, 255),
       (255, 255,   0, 255)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [90]:
# 22. Multiplicar una matiz de 5x3 por una de 3x2
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#np.ones((5, 3)) crea una matriz de tamaño 5x3, donde todos los elementos son 1
#np.ones((3, 2)) crea una matriz de tamaño 3x2, donde todos los elementos son 1
#La función np.dot se utiliza para calcular el producto matricial.
#El producto será una matiz de 5x2

In [91]:
# 23. Dado un array 1D, negar los elementos que estén entre 3 y 8 en su lugar
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [99]:
# 24. ¿Cuál es la salida del siguiente script?
print(sum(range(5),-1))
#En Python, suma los elementos del rango [0, 1, 2, 3, 4], y le suma -1 que da 9. Entonces la salida debería ser 9
from numpy import *
print(sum(range(5),-1))
#En NumPy, el segundo argumento especifica el eje a lo largo del cual se realiza la suma. Entonces la salida debería ser 10

10
10


In [100]:
#Determinar qué expresiones son legales para un array de enteros Z

#Z ** Z significa elevar cada elemento del array Z a sí mismo, elemento por elemento. Sin embargo, esta operación no está definida en el contexto de arrays 
Z**Z

ValueError: Integers to negative integer powers are not allowed.

In [101]:
2 << Z >> 2

array([  0,   1,   2,   4,   0,   0,   0,   0,   0, 256, 512], dtype=int32)

In [102]:
Z <- Z

array([False, False, False, False,  True,  True,  True,  True,  True,
       False, False])

In [103]:
1j*Z

array([ 0. +0.j,  0. +1.j,  0. +2.j,  0. +3.j, -0. -4.j, -0. -5.j,
       -0. -6.j, -0. -7.j, -0. -8.j,  0. +9.j,  0.+10.j])

In [104]:
Z/1/1

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7., -8.,  9., 10.])

In [105]:
Z<Z>Z
#En Python, las comparaciones encadenadas como x < y < z son evaluadas como (x < y) and (y < z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [106]:
# 26. ¿Cuáles son los resultados de las siguientes expresiones?

# 1
np.array(0) // np.array(0)
# Se produce un error de división por cero (ZeroDivisionError) porque tanto el numerador como el denominador son cero.

C:\Users\dania\AppData\Local\Temp\ipykernel_29856\3170485337.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [107]:
# 2
np.array(0) // np.array(0.)

C:\Users\dania\AppData\Local\Temp\ipykernel_29856\3559254148.py:1: RuntimeWarning: invalid value encountered in floor_divide
  np.array(0) // np.array(0.)


nan

In [108]:
# 3
np.array(0) / np.array(0)

C:\Users\dania\AppData\Local\Temp\ipykernel_29856\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [109]:
# 4
np.array(0) / np.array(0.)

C:\Users\dania\AppData\Local\Temp\ipykernel_29856\205773364.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0.)


nan

In [ ]:
# Las operaciones del 2 al 4 dan nan debido que se intenta dividir entre 0, lo que da como resultado una operación matemáticamente indefinida

In [110]:
# 27. Redondear un array de números flotantes lejos de cero
Z = np.random.uniform(-10,+10,10)
# Esto crea un array Z de tamaño 10 con valores flotantes aleatorios en el rango de -10 a +10 utilizando una distribución uniforme.
print (np.trunc(Z + np.copysign(0.5, Z)))
#Aquí, se suma 0.5 a los valores positivos de Z y se resta 0.5 a los valores negativos de Z, lo que tiene el efecto de desplazar los valores hacia arriba o hacia abajo
#Se aplica la función np.trunc() a la expresión obtenida en el paso anterior. Esta función retorna la parte entera de cada elemento, truncando cualquier parte decimal

[  6.   1.  -1.  -8. -10.  -4.   2.  -6.  -1.   5.]


In [111]:
# 28. Extraer la parte entera de un array aleatorio usando 5 métodos
Z = np.random.uniform(0,10,10)
Z

array([4.82614763, 7.54676139, 3.20025973, 9.01854233, 7.26636122,
       4.89279753, 0.60276061, 1.54114132, 5.07810816, 5.80724855])

In [112]:
print (Z - Z%1)

[4. 7. 3. 9. 7. 4. 0. 1. 5. 5.]


In [113]:
print (np.floor(Z))

[4. 7. 3. 9. 7. 4. 0. 1. 5. 5.]


In [114]:
print (np.ceil(Z)-1)

[4. 7. 3. 9. 7. 4. 0. 1. 5. 5.]


In [115]:
print (Z.astype(int))

[4 7 3 9 7 4 0 1 5 5]


In [116]:
print (np.trunc(Z))

[4. 7. 3. 9. 7. 4. 0. 1. 5. 5.]


In [117]:
# 29. Crear una matriz con valores de fila de rango 0 a 4
Z = np.zeros((5,5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [118]:
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [120]:
# 30. Generar una función que genera 10, y usarlos para construir un array
def generate():
    for x in range(10):
        yield x

#Cuando una función contiene la palabra clave yield, se convierte en un generador. 
#Cuando se llama a esta función, no se ejecuta completamente de una vez. En su lugar, se devuelve un iterador, y la ejecución de la función se pausa en la declaración yield
Z = np.fromiter(generate(), dtype=float, count=-1)
#np.fromiter() es una función de NumPy que crea un nuevo array a partir de un iterador.
#Cuando count es -1 (el valor predeterminado), np.fromiter() leerá todos los elementos del iterador hasta que este se agote.
print(Z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [121]:
# 31. Crear un array tamaño 10, valores de 0,1 deben ser exculidos
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
#La función np.linspace() genera un array de números espaciados uniformemente entre dos valores. 
#0: El valor de inicio del rango.
#1: El valor de finalización del rango.
#12: El número de elementos a generar en el array, incluyendo el punto final si endpoint=True.
#[1:-1]: Slicing que selecciona todos los elementos del array generado, excluye los valores de 0 y 1.
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [122]:
# 32. Generar un array random tamaño 10 y ordenarlo
Z = np.random.random(10)
Z

array([0.30404238, 0.46902737, 0.59831812, 0.86571454, 0.89083951,
       0.21954561, 0.21908091, 0.59966635, 0.73398091, 0.78200839])

In [123]:
Z.sort()
Z

array([0.21908091, 0.21954561, 0.30404238, 0.46902737, 0.59831812,
       0.59966635, 0.73398091, 0.78200839, 0.86571454, 0.89083951])

In [124]:
# 33. ¿Cómo sumar un array pequeño más rápido que np.sum?
Z = np.arange(10)
np.add.reduce(Z)
#Es más rápida que np.sum() para arrays pequeños porque está optimizada específicamente para la operación de suma.

45

In [125]:
# 34. Cosiderar 2 random arrays A y B, checar si son iguales
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
A

array([0, 1, 1, 1, 1])

In [126]:
B

array([1, 0, 0, 0, 0])

In [128]:
equal = np.allclose(A,B)
equal

False

In [129]:
# 35. Hacer que un array sea inmutable (solo lectura) 
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


ValueError: assignment destination is read-only

In [131]:
# 36. Considerar una matriz random 10x2 representando coordenadas cartesianas, y convertirlas a polares
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
#X,Y = Z[:,0], Z[:,1]: Divide la matriz Z en dos vectores X e Y, donde X contiene todas las coordenadas x y Y contiene todas las coordenadas y.
R = np.sqrt(X**2+Y**2)
# Calcula la magnitud (distancia radial) de las coordenadas polares a partir de las coordenadas cartesianas utilizando la fórmula de la distancia euclidiana.
T = np.arctan2(Y,X)
#Calcula el ángulo polar (dirección) de las coordenadas polares a partir de las coordenadas cartesianas
print(R)
#Imprime la magnitud de las coordenadas polares, que representan las distancias radiales de cada punto al origen.
print(T)
#Imprime el ángulo polar de las coordenadas polares, que representan las direcciones de cada punto con respecto al eje x positivo, en radianes.

[1.02652682 1.06166047 0.42313974 1.03888295 1.06457749 1.07053591
 0.8650111  0.56873738 1.07275966 0.76102139]
[0.32061118 0.87543088 0.71874009 0.79215924 0.39689224 1.18724109
 0.24737314 0.9017572  1.12965505 0.54343224]


In [132]:
# 37. Crear un vector aleatorio de tamaño 10 y reemplazar el valor máximo por un nuevo valor
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.38340245 0.07909993 0.60159657 0.38543227 0.69854102 0.1509462
 0.44017541 0.47472879 0.71621014 0.        ]


In [133]:
# 38. Crear un array estructurado que contenga las coordenadas x e y cubriendo el área [0,1]x[0,1]
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
#La función np.linspace(0,1,10) genera un array de 10 números espaciados uniformemente en el rango [0, 1]. 
#La función np.meshgrid() toma dos arrays de coordenadas (uno para x y otro para y) y devuelve dos matrices 2D que representan todas las combinaciones de coordenadas posibles.
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [134]:
#39. Dado 2 arrays, X y Y, construye la matriz de Cauchy
X = np.arange(8)
Y = X + 0.5
#Crea un vector Y que es el vector X desplazado por 0.5 en cada elemento. Esto asegura que los elementos de X y Y no sean idénticos 
#y evita divisiones por cero en la construcción de la matriz de Cauchy.
C = 1.0 / np.subtract.outer(X, Y)
#: Construye la matriz de Cauchy utilizando np.subtract.outer(), que calcula la diferencia entre cada elemento de X y cada elemento de Y. 
#Luego, cada elemento de esta diferencia se invierte para formar la matriz de Cauchy.
print(np.linalg.det(C))
#np.linalg.det(C): Calcula la determinante de la matriz C 

3638.1636371179666


In [135]:
# 40. Imprime el minimo y máximo de cada valor por cada tipo escalar en NumPy
for dtype in [np.int8, np.int32, np.int64]:
    #Esto itera sobre una lista de tipos de datos enteros de diferentes tamaños: int8, int32 y int64.
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [136]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    #print(np.finfo(dtype).eps): Imprime el épsilon de máquina para el tipo de dato actual.
    #El épsilon de máquina  es la menor diferencia entre 1 y el siguiente número mayor que puede ser representado por el tipo de dato.


-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [140]:
# 41. ¿Cómo imprimir todos los valores de un array?

#La opción threshold espera un valor numérico que representa el límite de elementos a mostrar antes de truncar la salida.
#np.set_printoptions(threshold=np.nan)
#Por lo tanto es erroneo usarlo así

#Lo correcto
np.set_printoptions(threshold=np.inf)
#Esto establecería el límite de impresión en infinito, lo que significa que NumPy imprimirá todos los elementos del array sin truncar la salida.
Z = np.zeros((25,25))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [142]:
#42. ¿Cómo encontrar el valor más cercano a un escalar dado en un array ?
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
#(np.abs(Z-v)).argmin(): Calcula las diferencias absolutas entre cada elemento de Z y el número aleatorio v, 
#luego encuentra el índice del valor mínimo de estas diferencias utilizando argmin().
print(Z[index])

19


In [144]:
# 43. Crear un array estructurado que represente una posición (x, y) y un color (r, g, b)
Z = np.zeros(10, dtype=[('position', [('x', float), ('y', float)]),
                        ('color', [('r', float), ('g', float), ('b', float)])])

print(Z)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [146]:
# 44. Considerar un vector forma (100,2), representando coordenadas, encontrar las distancias 
#punto por punto
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
#se utiliza para asegurarse de que una matriz tenga al menos dos dimensiones.

D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.58822574 0.73219215 0.41175438 0.42888457 0.79440891
  0.44272214 0.67243451 0.51728491 0.41835155]
 [0.58822574 0.         0.45565847 0.90983011 0.25955008 0.45366156
  0.14645286 0.95363372 0.948867   0.22988904]
 [0.73219215 0.45565847 0.         0.85043913 0.33642745 0.08255719
  0.48773261 0.70021965 0.81707246 0.61018261]
 [0.41175438 0.90983011 0.85043913 0.         0.6740709  0.93068415
  0.78071468 0.39033007 0.14310528 0.79814563]
 [0.42888457 0.25955008 0.33642745 0.6740709  0.         0.38181618
  0.19213658 0.69456797 0.69779982 0.3003298 ]
 [0.79440891 0.45366156 0.08255719 0.93068415 0.38181618 0.
  0.50975833 0.78094889 0.89938231 0.63250759]
 [0.44272214 0.14645286 0.48773261 0.78071468 0.19213658 0.50975833
  0.         0.86664738 0.83214938 0.12293156]
 [0.67243451 0.95363372 0.70021965 0.39033007 0.69456797 0.78094889
  0.86664738 0.         0.25718886 0.93500846]
 [0.51728491 0.948867   0.81707246 0.14310528 0.69779982 0.89938231
  0.83214938 0.25718

In [148]:
# Versión más rápida
import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


[[0.         0.20563338 0.66173668 0.44156068 0.09574675 0.63427362
  0.34847241 0.11055793 0.26172659 0.44918878]
 [0.20563338 0.         0.58117266 0.27732018 0.1944767  0.43812208
  0.40621838 0.11163267 0.42817367 0.38537812]
 [0.66173668 0.58117266 0.         0.35930441 0.72485372 0.76999483
  0.41051521 0.65327645 0.64070973 0.95517401]
 [0.44156068 0.27732018 0.35930441 0.         0.46425129 0.42862912
  0.41765015 0.38067949 0.56647256 0.61232865]
 [0.09574675 0.1944767  0.72485372 0.46425129 0.         0.58512545
  0.43978522 0.08398352 0.35227512 0.35562621]
 [0.63427362 0.43812208 0.76999483 0.42862912 0.58512545 0.
  0.79855403 0.52500163 0.86522006 0.44408711]
 [0.34847241 0.40621838 0.41051521 0.41765015 0.43978522 0.79855403
  0.         0.40450869 0.23253727 0.76980462]
 [0.11055793 0.11163267 0.65327645 0.38067949 0.08398352 0.52500163
  0.40450869 0.         0.36478123 0.36624714]
 [0.26172659 0.42817367 0.64070973 0.56647256 0.35227512 0.86522006
  0.23253727 0.36478

In [151]:
# 45. Convertir un array de tipo de dato de punto flotante (32 bits) en un array de tipo de dato entero (32 bits)
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print('-----')
print(Z)

[0 1 2 3 4 5 6 7 8 9]
-----
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [154]:
# 46. ¿Cómo leer el siguiente archivo?
# File content:
# -------------
#1,2,3,4,5
#6,,,7,8
#,,9,10,11
# -------------

#Z = np.genfromtxt("missing.dat", delimiter=",")
#Esta línea de código lee el archivo "missing.dat" utilizando np.genfromtxt(). 
#np.genfromtxt() intenta inferir el tipo de dato de cada columna en función de los valores que encuentra. Si encuentra valores que no son numéricos, 
#los considerará como valores faltantes o nan 

In [157]:
# 47. ¿Cuál es el equivalente de enumerate para los arrays de numpy
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [158]:
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [159]:
# 48. Generar un generico 2D a una distribución similar a una gaussiana
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [162]:
# 49. ¿Cómo colocar en lugares random elementos p en un array 2D?
n = 10
p = 3 # Número de elementos aleatorios a colocar
Z = np.zeros((n,n))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [163]:
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [166]:
# 50. Restar la media de cada fila de una matriz
X = np.random.rand(5, 10)
print(X)

[[0.03307246 0.57681039 0.72648546 0.22502452 0.69839532 0.96662374
  0.85376666 0.49992476 0.01162488 0.22966112]
 [0.59187075 0.23855163 0.25876326 0.14920281 0.54424132 0.06931702
  0.82633896 0.98343677 0.58840916 0.03901543]
 [0.99134619 0.34842118 0.39827209 0.9869142  0.64800058 0.91269786
  0.52264947 0.63062506 0.69522341 0.53414774]
 [0.06612664 0.87334825 0.97170818 0.71709832 0.92291603 0.4181469
  0.10702738 0.168622   0.10183232 0.25523997]
 [0.3111315  0.3231591  0.24325252 0.36052457 0.22919758 0.82861635
  0.49755579 0.42361258 0.50251928 0.98203271]]


In [167]:
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.44906647  0.09467146  0.24434653 -0.25711441  0.21625639  0.48448481
   0.37162773  0.01778583 -0.47051405 -0.25247781]
 [ 0.16295604 -0.19036308 -0.17015145 -0.2797119   0.11532661 -0.35959769
   0.39742425  0.55452206  0.15949445 -0.38989928]
 [ 0.32451641 -0.3184086  -0.26855769  0.32008443 -0.0188292   0.24586808
  -0.14418031 -0.03620472  0.02839363 -0.13268203]
 [-0.39407996  0.41314165  0.51150158  0.25689172  0.46270944 -0.0420597
  -0.35317922 -0.2915846  -0.35837428 -0.20496663]
 [-0.1590287  -0.1470011  -0.22690768 -0.10963563 -0.24096261  0.35845615
   0.02739559 -0.04654762  0.03235908  0.51187251]]


In [168]:
# 51. ¿Cómo ordenar un array por la columna n-ésima?
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 4 1]
 [9 6 3]
 [4 5 0]]
[[7 4 1]
 [4 5 0]
 [9 6 3]]


In [169]:
# 52. ¿Cómo determinar si un array 2D dado tiene columnas nulas?
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())


False


In [170]:
# 53. Encontrar el valor más cercano dado un valor en un array
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4840972197412411


In [171]:
# 54. Crear una class tipo array que tenga que tenga un atributo de nombre
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

In [172]:
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [174]:
# 55. Considerar un vector dado, ¿cómo añadir un 1 a cada elemento indexado por un segundo vector, teniendo en cuenta índices repetidos?
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 4. 3. 2. 3. 2. 3. 2. 3. 4.]


In [175]:
# 56. ¿Cómo acumular elementos de un vector (X) en un array (F) basado en una lista de índices (I)?
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [176]:
# 57. Considerando una imagen con dimensiones (w, h, 3) donde cada píxel se representa con tres valores para los canales de color (rojo, verde y azul) y cada valor se almacena como un byte sin signo (dtype=ubyte). 
#Calcular el número de colores únicos presentes en la imagen
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))


[0 1]


In [177]:
# 58. Considerando un array de cuatro dimensiones, ¿cómo sumar sobre los dos últimos ejes
#a la vez
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[47 62 40 31]
 [34 54 50 48]
 [59 70 52 72]]


In [178]:
# 59. Considerando un arreglo unidimensional vector D, ¿cómo calcular las medias de los subconjuntos de un vector 
# utilizando un vector S del mismo tamaño que describe los índices de los subconjuntos?
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.46437956 0.67150175 0.44724326 0.20174078 0.57133403 0.44075884
 0.60638618 0.40660678 0.55292061 0.50662592]
