# <font color='purple'> **100 NUMPY EXERCISES** </font>

<font color = 'gray'> *Author: Dania Garcia | 9° IDGS* </font>

In [2]:
# 1. Importar paquete de Numpy
import numpy as np

In [3]:
# 2.1 Conocer versión del paquete
print(np.__version__)

1.26.3


In [13]:
# 2.2 Conocer la configuración
# # 'stdout' -> lo que significa que la información se imprimirá en la salida estándar (normalmente la consola o terminal).
np.show_config

<function numpy.__config__.show(mode='stdout')>

In [6]:
# 3. Crear arreglo tamaño 10 con ceros
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# 4. Obtener documentación con salida en consola. 
# Usar help()
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [15]:
# 5. Hacer que el arreglo del ejercicio 3, el quinto valor sea 1
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
# 6. Crear un array con valores de 10 a 49
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [22]:
# 7. Hacer que el primer elemento sea el último
Z = np.arange(50)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [32]:
# 8. Crear una matriz de 3x3 de 0 a 8
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
# 9. Encontrar los índices que sean distintos a 0 de [1,2,0,0,4,0]
list = [1,2,0,0,4,0]
nz = np.array(list)
nz

array([1, 2, 0, 0, 4, 0])

In [38]:
nz_indices = np.nonzero(nz)
nz_indices

(array([0, 1, 4], dtype=int64),)

In [39]:
# 10. Crear una matriz 3x3, donde se haga una diagonal con los valores 1, y los demás 0
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# 11. Crear un array 3x3x3, con valore ramdom
z = np.random.random((3,3,3))
z

array([[[0.47094787, 0.50052978, 0.12784304],
        [0.80929327, 0.37496596, 0.22191741],
        [0.95937577, 0.59731364, 0.79275145]],

       [[0.5352274 , 0.18401084, 0.30195513],
        [0.66850553, 0.02857294, 0.50745207],
        [0.5999396 , 0.75599135, 0.38383778]],

       [[0.325648  , 0.91102252, 0.39065356],
        [0.12488378, 0.40777273, 0.30467937],
        [0.08020944, 0.23095711, 0.04819253]]])

In [41]:
# 12.1 Crear un array 10x10 con valores random
z = np.random.random((10,10))
z

array([[0.33326845, 0.14762897, 0.57446378, 0.24698238, 0.79554277,
        0.27163661, 0.51430122, 0.85363651, 0.8063002 , 0.14136332],
       [0.13320266, 0.02634857, 0.40761292, 0.53652191, 0.52010262,
        0.10693905, 0.78880148, 0.56565583, 0.98015484, 0.90174415],
       [0.49427208, 0.39450744, 0.13110049, 0.52439308, 0.0639171 ,
        0.88871241, 0.04171208, 0.48127131, 0.28483996, 0.09805838],
       [0.79008168, 0.84024483, 0.65368072, 0.11309008, 0.62540935,
        0.06780578, 0.20595332, 0.36324379, 0.05808351, 0.0612546 ],
       [0.51071802, 0.0902673 , 0.04623361, 0.86063079, 0.3536545 ,
        0.25624377, 0.44334331, 0.4189069 , 0.19394975, 0.22591767],
       [0.61369966, 0.30223577, 0.6952809 , 0.05939026, 0.20853989,
        0.6256457 , 0.92139165, 0.5819683 , 0.73621308, 0.1279503 ],
       [0.44273131, 0.03421683, 0.87325245, 0.78659703, 0.15323609,
        0.84060837, 0.28789453, 0.01524901, 0.0906923 , 0.92036863],
       [0.33774084, 0.14589551, 0.3641136

In [45]:
#12.2 Encontrar las valores máximos y mínimos
Zmin, Zmax = z.min(), z.max()
Zmin

0.01365740486348932

In [46]:
Zmax

0.9969700754861458

In [51]:
# 13.1 Crear un vector de 30 con valores random
low = 1
high = 100
z = np.random.randint(low,high,size=30)
z

array([74, 14, 18, 57, 37, 61, 53, 19, 64, 23, 67, 96, 89, 46, 97, 99, 64,
       94, 15, 32, 27,  4, 17, 34, 74, 16, 27, 78, 95, 58])

In [52]:
# 13.2 Encontrar el promedio
z_promedio = np.mean(z)
z_promedio

51.63333333333333

In [53]:
# 14. Crear un array 2d con 1 en el borde, y 0  adentro
z = np.ones((10,10))
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [56]:
z[1:-1,1:-1] = 0
#1:-1: Este slicing indica que estamos seleccionando todas las filas y columnas del array z, excepto la primera y la última fila
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [62]:
# 15. ¿Qué resultado se obtiene de la siguuiente expresión?
0 * np.nan
# Cualquier operación con un valor NaN también produce un resultado NaN.


nan

In [65]:
np.nan == np.nan
#Dos valores NaN no son considerados iguales. Esto es porque NaN representa un valor indeterminado o no definido, 
#y no tiene un sentido definido de igualdad

False

In [66]:
np.inf > np.nan
#Cualquier comparación con NaN (incluso con infinito) generalmente devuelve False.

False

In [63]:
np.nan - np.nan
#cualquier operación con un valor NaN también produce un resultado NaN.

nan

In [64]:
0.3 == 3 * 0.1
# la forma en que se almacenan los números de punto flotante en la computadora y cómo se realizan  
# las operaciones aritméticas con ellos, la comparación puede no dar el resultado esperado.

False

In [67]:
#16. Crea una matriz 5x5 con valores de 1-4 en la diagonal
Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
#np.arange(4): Esta función crea un array que contiene los números [0, 1, 2, 3].

#1+np.arange(4): Le sumamos 1 a cada elemento del array, obteniendo [1, 2, 3, 4].

#np.diag(1+np.arange(4), k=-1): Esta función crea una matriz diagonal con los elementos de [1, 2, 3, 4] 
#en su diagonal principal, desplazados una posición hacia abajo (k=-1).

In [69]:
#17. Crear una matriz de 8x8 e inicializarla con un patrón de tablero de ajedrez usando NumPy
tablero = np.zeros((8,8), dtype=int)
tablero

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [70]:
#Rellenar filas impares con unos
tablero[1::2, ::2] = 1
tablero

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [71]:
#Rellenar filas pares con unos
tablero[::2, 1::2] = 1
tablero

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [72]:
#18. Determinar los índices (x, y, z) del elemento 100 en un array de forma (6, 7, 8)
print(np.unravel_index(100,(6,7,8)))
#6 capas, 7 filas por cada capa, 8 columnas por cada fila

(1, 5, 4)


In [73]:
#19. Crear un tablero de ajedréz usando la función .tile
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [74]:
#np.tile(..., (4, 4)): Esta es la función np.tile() que toma dos argumentos: el patrón básico y una tupla que indica
#El primer argumento (np.array([[0,1],[1,0]])) es el patrón básico que queremos repetir.
#El segundo argumento (4, 4) indica que queremos repetir el patrón 4 veces tanto en el eje de las filas como en el eje de las columnas.

In [81]:
# 20. Normalizar una matriz aleatoria de 5x5 
# Hacer que todos los valores esten en el rango de [0,1]
z = np.random.random((5,5))
z

array([[0.18775848, 0.12781712, 0.57959282, 0.81331432, 0.70044032],
       [0.51258757, 0.526064  , 0.42036499, 0.02014312, 0.76945581],
       [0.66745958, 0.42842362, 0.46215324, 0.81040149, 0.13132288],
       [0.55169751, 0.63895553, 0.22707144, 0.06970215, 0.14024199],
       [0.53514576, 0.26662421, 0.0102684 , 0.290004  , 0.36724052]])

In [82]:
zmax, zmin = z.max(), z.min()
z = (z - zmin)/(zmax - zmin)
z

array([[0.22102108, 0.14637858, 0.70895624, 1.        , 0.85944266],
       [0.62551736, 0.64229901, 0.51067639, 0.01229658, 0.94538481],
       [0.81837309, 0.52071147, 0.56271357, 0.99637277, 0.15074415],
       [0.67421936, 0.78287818, 0.26997589, 0.07401041, 0.16185076],
       [0.65360815, 0.31922933, 0.        , 0.34834322, 0.44452267]])

In [88]:
# 21. Crear un tipo de dato personalizado que describa un color como cuatro bytes sin signo (R, G, B, A)
color_dtype = np.dtype([("r", np.uint8), 
                  ("g", np.uint8), 
                  ("b", np.uint8), 
                  ("a", np.uint8)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [89]:
colors = np.array([(255, 0, 0, 255),    # Rojo
                   (0, 255, 0, 255),    # Verde
                   (0, 0, 255, 255),    # Azul
                   (255, 255, 0, 255)   # Amarillo
], dtype=color_dtype)

colors

array([(255,   0,   0, 255), (  0, 255,   0, 255), (  0,   0, 255, 255),
       (255, 255,   0, 255)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [90]:
# 22. Multiplicar una matiz de 5x3 por una de 3x2
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#np.ones((5, 3)) crea una matriz de tamaño 5x3, donde todos los elementos son 1
#np.ones((3, 2)) crea una matriz de tamaño 3x2, donde todos los elementos son 1
#La función np.dot se utiliza para calcular el producto matricial.
#El producto será una matiz de 5x2

In [91]:
# 23. Dado un array 1D, negar los elementos que estén entre 3 y 8 en su lugar
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [99]:
# 24. ¿Cuál es la salida del siguiente script?
print(sum(range(5),-1))
#En Python, suma los elementos del rango [0, 1, 2, 3, 4], y le suma -1 que da 9. Entonces la salida debería ser 9
from numpy import *
print(sum(range(5),-1))
#En NumPy, el segundo argumento especifica el eje a lo largo del cual se realiza la suma. Entonces la salida debería ser 10

10
10


In [100]:
#Determinar qué expresiones son legales para un array de enteros Z

#Z ** Z significa elevar cada elemento del array Z a sí mismo, elemento por elemento. Sin embargo, esta operación no está definida en el contexto de arrays 
Z**Z

ValueError: Integers to negative integer powers are not allowed.

In [101]:
2 << Z >> 2

array([  0,   1,   2,   4,   0,   0,   0,   0,   0, 256, 512], dtype=int32)

In [102]:
Z <- Z

array([False, False, False, False,  True,  True,  True,  True,  True,
       False, False])

In [103]:
1j*Z

array([ 0. +0.j,  0. +1.j,  0. +2.j,  0. +3.j, -0. -4.j, -0. -5.j,
       -0. -6.j, -0. -7.j, -0. -8.j,  0. +9.j,  0.+10.j])

In [104]:
Z/1/1

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7., -8.,  9., 10.])

In [105]:
Z<Z>Z
#En Python, las comparaciones encadenadas como x < y < z son evaluadas como (x < y) and (y < z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [106]:
# 26. ¿Cuáles son los resultados de las siguientes expresiones?

# 1
np.array(0) // np.array(0)
# Se produce un error de división por cero (ZeroDivisionError) porque tanto el numerador como el denominador son cero.

C:\Users\dania\AppData\Local\Temp\ipykernel_29856\3170485337.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [107]:
# 2
np.array(0) // np.array(0.)

C:\Users\dania\AppData\Local\Temp\ipykernel_29856\3559254148.py:1: RuntimeWarning: invalid value encountered in floor_divide
  np.array(0) // np.array(0.)


nan

In [108]:
# 3
np.array(0) / np.array(0)

C:\Users\dania\AppData\Local\Temp\ipykernel_29856\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [109]:
# 4
np.array(0) / np.array(0.)

C:\Users\dania\AppData\Local\Temp\ipykernel_29856\205773364.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0.)


nan

In [ ]:
# Las operaciones del 2 al 4 dan nan debido que se intenta dividir entre 0, lo que da como resultado una operación matemáticamente indefinida

In [110]:
# 27. Redondear un array de números flotantes lejos de cero
Z = np.random.uniform(-10,+10,10)
# Esto crea un array Z de tamaño 10 con valores flotantes aleatorios en el rango de -10 a +10 utilizando una distribución uniforme.
print (np.trunc(Z + np.copysign(0.5, Z)))
#Aquí, se suma 0.5 a los valores positivos de Z y se resta 0.5 a los valores negativos de Z, lo que tiene el efecto de desplazar los valores hacia arriba o hacia abajo
#Se aplica la función np.trunc() a la expresión obtenida en el paso anterior. Esta función retorna la parte entera de cada elemento, truncando cualquier parte decimal

[  6.   1.  -1.  -8. -10.  -4.   2.  -6.  -1.   5.]


In [111]:
# 28. Extraer la parte entera de un array aleatorio usando 5 métodos
Z = np.random.uniform(0,10,10)
Z

array([4.82614763, 7.54676139, 3.20025973, 9.01854233, 7.26636122,
       4.89279753, 0.60276061, 1.54114132, 5.07810816, 5.80724855])

In [112]:
print (Z - Z%1)

[4. 7. 3. 9. 7. 4. 0. 1. 5. 5.]


In [113]:
print (np.floor(Z))

[4. 7. 3. 9. 7. 4. 0. 1. 5. 5.]


In [114]:
print (np.ceil(Z)-1)

[4. 7. 3. 9. 7. 4. 0. 1. 5. 5.]


In [115]:
print (Z.astype(int))

[4 7 3 9 7 4 0 1 5 5]


In [116]:
print (np.trunc(Z))

[4. 7. 3. 9. 7. 4. 0. 1. 5. 5.]


In [117]:
# 29. Crear una matriz con valores de fila de rango 0 a 4
Z = np.zeros((5,5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [118]:
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])