# <font color='purple'> **100 NUMPY EXERCISES** </font>

<font color = 'gray'> *Author: Dania Garcia | 9° IDGS* </font>

In [2]:
# 1. Importar paquete de Numpy
import numpy as np

In [3]:
# 2.1 Conocer versión del paquete
print(np.__version__)

1.26.3


In [4]:
# 2.2 Conocer la configuración
# # 'stdout' -> lo que significa que la información se imprimirá en la salida estándar (normalmente la consola o terminal).
np.show_config

<function numpy.__config__.show(mode='stdout')>

In [5]:
# 3. Crear arreglo tamaño 10 con ceros
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# 4. Obtener documentación con salida en consola. 
# Usar help()
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [91]:
# 5. Hacer que el arreglo del ejercicio 3, el quinto valor sea 1
Z

array([[7, 9, 9, 5, 4, 3, 3, 0, 7, 6],
       [7, 0, 8, 1, 8, 3, 2, 1, 7, 6],
       [8, 0, 4, 9, 1, 1, 9, 8, 2, 1],
       [7, 8, 6, 0, 8, 0, 4, 4, 6, 9],
       [0, 1, 4, 8, 9, 7, 2, 2, 0, 0],
       [0, 5, 7, 3, 5, 1, 7, 9, 2, 8],
       [8, 4, 2, 7, 7, 1, 7, 2, 5, 5],
       [3, 1, 0, 5, 5, 7, 9, 4, 0, 5],
       [0, 5, 6, 3, 0, 0, 0, 9, 2, 3],
       [8, 5, 7, 6, 1, 9, 3, 3, 2, 9]])

In [92]:
Z[4] = 1
Z

array([[7, 9, 9, 5, 4, 3, 3, 0, 7, 6],
       [7, 0, 8, 1, 8, 3, 2, 1, 7, 6],
       [8, 0, 4, 9, 1, 1, 9, 8, 2, 1],
       [7, 8, 6, 0, 8, 0, 4, 4, 6, 9],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 5, 7, 3, 5, 1, 7, 9, 2, 8],
       [8, 4, 2, 7, 7, 1, 7, 2, 5, 5],
       [3, 1, 0, 5, 5, 7, 9, 4, 0, 5],
       [0, 5, 6, 3, 0, 0, 0, 9, 2, 3],
       [8, 5, 7, 6, 1, 9, 3, 3, 2, 9]])

In [94]:
# 6. Crear un array con valores de 10 a 49
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
# 7. Hacer que el primer elemento sea el último
Z = np.arange(50)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [95]:
# 8. Crear una matriz de 3x3 de 0 a 8
Z = np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
# 9. Encontrar los índices que sean distintos a 0 de [1,2,0,0,4,0]
list = [1,2,0,0,4,0]
nz = np.array(list)
nz

array([1, 2, 0, 0, 4, 0])

In [14]:
nz_indices = np.nonzero(nz)
nz_indices

(array([0, 1, 4], dtype=int64),)

In [15]:
# 10. Crear una matriz 3x3, donde se haga una diagonal con los valores 1, y los demás 0
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# 11. Crear un array 3x3x3, con valore ramdom
z = np.random.random((3,3,3))
z

array([[[0.62135931, 0.08804312, 0.14046254],
        [0.07311979, 0.05464711, 0.3441073 ],
        [0.64724877, 0.45004883, 0.08040674]],

       [[0.62367925, 0.55120284, 0.90767171],
        [0.80800567, 0.41812658, 0.75007778],
        [0.2173775 , 0.25493775, 0.99763927]],

       [[0.34189325, 0.36565853, 0.04545763],
        [0.96539898, 0.59620998, 0.3084397 ],
        [0.10416989, 0.00183752, 0.44033418]]])

In [17]:
# 12.1 Crear un array 10x10 con valores random
z = np.random.random((10,10))
z

array([[0.84229301, 0.97043217, 0.61348467, 0.21574846, 0.54990902,
        0.8005654 , 0.60400697, 0.31954126, 0.63730737, 0.5001942 ],
       [0.7190926 , 0.35714569, 0.69841036, 0.14517841, 0.0719212 ,
        0.74688657, 0.63192384, 0.08147069, 0.11798254, 0.51989598],
       [0.09718376, 0.26022344, 0.74293883, 0.09754412, 0.67226145,
        0.68279549, 0.2745341 , 0.35905014, 0.427583  , 0.75015039],
       [0.54280087, 0.44683752, 0.96922016, 0.28469788, 0.38623041,
        0.07923241, 0.07573125, 0.69827442, 0.27885375, 0.44048999],
       [0.15747277, 0.953951  , 0.45159893, 0.72734542, 0.52297804,
        0.24315429, 0.80678227, 0.91309797, 0.43570316, 0.3648255 ],
       [0.49099655, 0.37602325, 0.24557834, 0.39707712, 0.62095835,
        0.25803741, 0.28780428, 0.36408753, 0.66210307, 0.88564277],
       [0.54203195, 0.25803575, 0.8908872 , 0.89768147, 0.09631298,
        0.83716581, 0.68925512, 0.40409707, 0.75164498, 0.29681671],
       [0.76734978, 0.60798151, 0.6598204

In [18]:
#12.2 Encontrar las valores máximos y mínimos
Zmin, Zmax = z.min(), z.max()
Zmin

0.014561360875183893

In [19]:
Zmax

0.9704321653114797

In [20]:
# 13.1 Crear un vector de 30 con valores random
low = 1
high = 100
z = np.random.randint(low,high,size=30)
z

array([66, 52, 86, 77, 44,  5,  8, 11, 63, 31, 69, 23, 25, 32, 53, 12, 85,
       35,  3, 64, 16, 78, 27, 41, 16, 49,  8, 47, 27, 26])

In [21]:
# 13.2 Encontrar el promedio
z_promedio = np.mean(z)
z_promedio

39.3

In [22]:
# 14. Crear un array 2d con 1 en el borde, y 0  adentro
z = np.ones((10,10))
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
z[1:-1,1:-1] = 0
#1:-1: Este slicing indica que estamos seleccionando todas las filas y columnas del array z, excepto la primera y la última fila
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
# 15. ¿Qué resultado se obtiene de la siguuiente expresión?
0 * np.nan
# Cualquier operación con un valor NaN también produce un resultado NaN.


nan

In [25]:
np.nan == np.nan
#Dos valores NaN no son considerados iguales. Esto es porque NaN representa un valor indeterminado o no definido, 
#y no tiene un sentido definido de igualdad

False

In [26]:
np.inf > np.nan
#Cualquier comparación con NaN (incluso con infinito) generalmente devuelve False.

False

In [27]:
np.nan - np.nan
#cualquier operación con un valor NaN también produce un resultado NaN.

nan

In [28]:
0.3 == 3 * 0.1
# la forma en que se almacenan los números de punto flotante en la computadora y cómo se realizan  
# las operaciones aritméticas con ellos, la comparación puede no dar el resultado esperado.

False

In [29]:
#16. Crea una matriz 5x5 con valores de 1-4 en la diagonal
Z = np.diag(1+np.arange(4),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [30]:
#np.arange(4): Esta función crea un array que contiene los números [0, 1, 2, 3].

#1+np.arange(4): Le sumamos 1 a cada elemento del array, obteniendo [1, 2, 3, 4].

#np.diag(1+np.arange(4), k=-1): Esta función crea una matriz diagonal con los elementos de [1, 2, 3, 4] 
#en su diagonal principal, desplazados una posición hacia abajo (k=-1).

In [31]:
#17. Crear una matriz de 8x8 e inicializarla con un patrón de tablero de ajedrez usando NumPy
tablero = np.zeros((8,8), dtype=int)
tablero

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
#Rellenar filas impares con unos
tablero[1::2, ::2] = 1
tablero

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [33]:
#Rellenar filas pares con unos
tablero[::2, 1::2] = 1
tablero

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [34]:
#18. Determinar los índices (x, y, z) del elemento 100 en un array de forma (6, 7, 8)
print(np.unravel_index(100,(6,7,8)))
#6 capas, 7 filas por cada capa, 8 columnas por cada fila

(1, 5, 4)


In [35]:
#19. Crear un tablero de ajedréz usando la función .tile
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [36]:
#np.tile(..., (4, 4)): Esta es la función np.tile() que toma dos argumentos: el patrón básico y una tupla que indica
#El primer argumento (np.array([[0,1],[1,0]])) es el patrón básico que queremos repetir.
#El segundo argumento (4, 4) indica que queremos repetir el patrón 4 veces tanto en el eje de las filas como en el eje de las columnas.

In [37]:
# 20. Normalizar una matriz aleatoria de 5x5 
# Hacer que todos los valores esten en el rango de [0,1]
z = np.random.random((5,5))
z

array([[0.34957546, 0.20358892, 0.50134587, 0.01302754, 0.02695692],
       [0.41266506, 0.67234794, 0.74988516, 0.68538282, 0.33847752],
       [0.002758  , 0.15287372, 0.02103025, 0.16007644, 0.39031602],
       [0.13587278, 0.32790116, 0.89712704, 0.42572109, 0.92307779],
       [0.95926167, 0.36227178, 0.14815799, 0.31739654, 0.13588389]])

In [38]:
zmax, zmin = z.max(), z.min()
z = (z - zmin)/(zmax - zmin)
z

array([[0.36258874, 0.20996357, 0.5212608 , 0.01073654, 0.02529934],
       [0.42854729, 0.70003907, 0.78110224, 0.7136667 , 0.35098613],
       [0.        , 0.15694213, 0.01910317, 0.16447238, 0.40518195],
       [0.13916808, 0.33992881, 0.93503984, 0.44219704, 0.96217068],
       [1.        , 0.37586242, 0.15201195, 0.32894651, 0.1391797 ]])

In [39]:
# 21. Crear un tipo de dato personalizado que describa un color como cuatro bytes sin signo (R, G, B, A)
color_dtype = np.dtype([("r", np.uint8), 
                  ("g", np.uint8), 
                  ("b", np.uint8), 
                  ("a", np.uint8)])
color

NameError: name 'color' is not defined

In [48]:
colors = np.array([(255, 0, 0, 255),    # Rojo
                   (0, 255, 0, 255),    # Verde
                   (0, 0, 255, 255),    # Azul
                   (255, 255, 0, 255)   # Amarillo
], dtype=color_dtype)

colors

array([(255,   0,   0, 255), (  0, 255,   0, 255), (  0,   0, 255, 255),
       (255, 255,   0, 255)],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [47]:
# 22. Multiplicar una matiz de 5x3 por una de 3x2
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#np.ones((5, 3)) crea una matriz de tamaño 5x3, donde todos los elementos son 1
#np.ones((3, 2)) crea una matriz de tamaño 3x2, donde todos los elementos son 1
#La función np.dot se utiliza para calcular el producto matricial.
#El producto será una matiz de 5x2

In [46]:
# 23. Dado un array 1D, negar los elementos que estén entre 3 y 8 en su lugar
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [49]:
# 24. ¿Cuál es la salida del siguiente script?
print(sum(range(5),-1))
#En Python, suma los elementos del rango [0, 1, 2, 3, 4], y le suma -1 que da 9. Entonces la salida debería ser 9
from numpy import *
print(sum(range(5),-1))
#En NumPy, el segundo argumento especifica el eje a lo largo del cual se realiza la suma. Entonces la salida debería ser 10

9
10


In [50]:
#Determinar qué expresiones son legales para un array de enteros Z

#Z ** Z significa elevar cada elemento del array Z a sí mismo, elemento por elemento. Sin embargo, esta operación no está definida en el contexto de arrays 
Z**Z

array([[27., 27.],
       [27., 27.],
       [27., 27.],
       [27., 27.],
       [27., 27.]])

In [51]:
2 << Z >> 2

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [52]:
Z <- Z

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [ ]:
1j*Z

In [ ]:
Z/1/1

In [ ]:
Z<Z>Z
#En Python, las comparaciones encadenadas como x < y < z son evaluadas como (x < y) and (y < z)

In [ ]:
# 26. ¿Cuáles son los resultados de las siguientes expresiones?

# 1
np.array(0) // np.array(0)
# Se produce un error de división por cero (ZeroDivisionError) porque tanto el numerador como el denominador son cero.

In [ ]:
# 2
np.array(0) // np.array(0.)

In [ ]:
# 3
np.array(0) / np.array(0)

In [ ]:
# 4
np.array(0) / np.array(0.)

In [ ]:
# Las operaciones del 2 al 4 dan nan debido que se intenta dividir entre 0, lo que da como resultado una operación matemáticamente indefinida

In [ ]:
# 27. Redondear un array de números flotantes lejos de cero
Z = np.random.uniform(-10,+10,10)
# Esto crea un array Z de tamaño 10 con valores flotantes aleatorios en el rango de -10 a +10 utilizando una distribución uniforme.
print (np.trunc(Z + np.copysign(0.5, Z)))
#Aquí, se suma 0.5 a los valores positivos de Z y se resta 0.5 a los valores negativos de Z, lo que tiene el efecto de desplazar los valores hacia arriba o hacia abajo
#Se aplica la función np.trunc() a la expresión obtenida en el paso anterior. Esta función retorna la parte entera de cada elemento, truncando cualquier parte decimal

In [ ]:
# 28. Extraer la parte entera de un array aleatorio usando 5 métodos
Z = np.random.uniform(0,10,10)
Z

In [ ]:
print (Z - Z%1)

In [ ]:
print (np.floor(Z))

In [ ]:
print (np.ceil(Z)-1)

In [ ]:
print (Z.astype(int))

In [ ]:
print (np.trunc(Z))

In [ ]:
# 29. Crear una matriz con valores de fila de rango 0 a 4
Z = np.zeros((5,5))
Z

In [ ]:
Z += np.arange(5)
Z

In [ ]:
# 30. Generar una función que genera 10, y usarlos para construir un array
def generate():
    for x in range(10):
        yield x

#Cuando una función contiene la palabra clave yield, se convierte en un generador. 
#Cuando se llama a esta función, no se ejecuta completamente de una vez. En su lugar, se devuelve un iterador, y la ejecución de la función se pausa en la declaración yield
Z = np.fromiter(generate(), dtype=float, count=-1)
#np.fromiter() es una función de NumPy que crea un nuevo array a partir de un iterador.
#Cuando count es -1 (el valor predeterminado), np.fromiter() leerá todos los elementos del iterador hasta que este se agote.
print(Z)


In [ ]:
# 31. Crear un array tamaño 10, valores de 0,1 deben ser exculidos
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
#La función np.linspace() genera un array de números espaciados uniformemente entre dos valores. 
#0: El valor de inicio del rango.
#1: El valor de finalización del rango.
#12: El número de elementos a generar en el array, incluyendo el punto final si endpoint=True.
#[1:-1]: Slicing que selecciona todos los elementos del array generado, excluye los valores de 0 y 1.
print(Z)

In [ ]:
# 32. Generar un array random tamaño 10 y ordenarlo
Z = np.random.random(10)
Z

In [ ]:
Z.sort()
Z

In [ ]:
# 33. ¿Cómo sumar un array pequeño más rápido que np.sum?
Z = np.arange(10)
np.add.reduce(Z)
#Es más rápida que np.sum() para arrays pequeños porque está optimizada específicamente para la operación de suma.

In [41]:
# 34. Cosiderar 2 random arrays A y B, checar si son iguales
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
A

array([0, 1, 1, 0, 1])

In [ ]:
B

In [42]:
equal = np.allclose(A,B)
equal

False

In [43]:
# 35. Hacer que un array sea inmutable (solo lectura) 
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


ValueError: assignment destination is read-only

In [44]:
# 36. Considerar una matriz random 10x2 representando coordenadas cartesianas, y convertirlas a polares
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
#X,Y = Z[:,0], Z[:,1]: Divide la matriz Z en dos vectores X e Y, donde X contiene todas las coordenadas x y Y contiene todas las coordenadas y.
R = np.sqrt(X**2+Y**2)
# Calcula la magnitud (distancia radial) de las coordenadas polares a partir de las coordenadas cartesianas utilizando la fórmula de la distancia euclidiana.
T = np.arctan2(Y,X)
#Calcula el ángulo polar (dirección) de las coordenadas polares a partir de las coordenadas cartesianas
print(R)
#Imprime la magnitud de las coordenadas polares, que representan las distancias radiales de cada punto al origen.
print(T)
#Imprime el ángulo polar de las coordenadas polares, que representan las direcciones de cada punto con respecto al eje x positivo, en radianes.

[0.79466887 0.43794565 0.69304403 0.64481134 1.20466285 0.87322884
 0.14266512 0.47044808 0.92015002 0.84726457]
[1.08388058 0.76110091 1.12050092 0.83429836 0.67954621 0.99478774
 1.23013888 0.34700186 0.09766824 0.32639443]


In [54]:
# 37. Crear un vector aleatorio de tamaño 10 y reemplazar el valor máximo por un nuevo valor
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.23658941 0.34085786 0.63191195 0.36454945 0.         0.3743111
 0.82289108 0.66411261 0.59530156 0.64587801]


In [53]:
# 38. Crear un array estructurado que contenga las coordenadas x e y cubriendo el área [0,1]x[0,1]
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
#La función np.linspace(0,1,10) genera un array de 10 números espaciados uniformemente en el rango [0, 1]. 
#La función np.meshgrid() toma dos arrays de coordenadas (uno para x y otro para y) y devuelve dos matrices 2D que representan todas las combinaciones de coordenadas posibles.
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [ ]:
#39. Dado 2 arrays, X y Y, construye la matriz de Cauchy
X = np.arange(8)
Y = X + 0.5
#Crea un vector Y que es el vector X desplazado por 0.5 en cada elemento. Esto asegura que los elementos de X y Y no sean idénticos 
#y evita divisiones por cero en la construcción de la matriz de Cauchy.
C = 1.0 / np.subtract.outer(X, Y)
#: Construye la matriz de Cauchy utilizando np.subtract.outer(), que calcula la diferencia entre cada elemento de X y cada elemento de Y. 
#Luego, cada elemento de esta diferencia se invierte para formar la matriz de Cauchy.
print(np.linalg.det(C))
#np.linalg.det(C): Calcula la determinante de la matriz C 

In [ ]:
# 40. Imprime el minimo y máximo de cada valor por cada tipo escalar en NumPy
for dtype in [np.int8, np.int32, np.int64]:
    #Esto itera sobre una lista de tipos de datos enteros de diferentes tamaños: int8, int32 y int64.
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

In [ ]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    #print(np.finfo(dtype).eps): Imprime el épsilon de máquina para el tipo de dato actual.
    #El épsilon de máquina  es la menor diferencia entre 1 y el siguiente número mayor que puede ser representado por el tipo de dato.


In [ ]:
# 41. ¿Cómo imprimir todos los valores de un array?

#La opción threshold espera un valor numérico que representa el límite de elementos a mostrar antes de truncar la salida.
#np.set_printoptions(threshold=np.nan)
#Por lo tanto es erroneo usarlo así

#Lo correcto
np.set_printoptions(threshold=np.inf)
#Esto establecería el límite de impresión en infinito, lo que significa que NumPy imprimirá todos los elementos del array sin truncar la salida.
Z = np.zeros((25,25))
Z

In [ ]:
#42. ¿Cómo encontrar el valor más cercano a un escalar dado en un array ?
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
#(np.abs(Z-v)).argmin(): Calcula las diferencias absolutas entre cada elemento de Z y el número aleatorio v, 
#luego encuentra el índice del valor mínimo de estas diferencias utilizando argmin().
print(Z[index])

In [ ]:
# 43. Crear un array estructurado que represente una posición (x, y) y un color (r, g, b)
Z = np.zeros(10, dtype=[('position', [('x', float), ('y', float)]),
                        ('color', [('r', float), ('g', float), ('b', float)])])

print(Z)


In [ ]:
# 44. Considerar un vector forma (100,2), representando coordenadas, encontrar las distancias 
#punto por punto
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
#se utiliza para asegurarse de que una matriz tenga al menos dos dimensiones.

D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

In [ ]:
# Versión más rápida
import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)


In [55]:
# 45. Convertir un array de tipo de dato de punto flotante (32 bits) en un array de tipo de dato entero (32 bits)
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print('-----')
print(Z)

[0 1 2 3 4 5 6 7 8 9]
-----
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
# 46. ¿Cómo leer el siguiente archivo?
# File content:
# -------------
#1,2,3,4,5
#6,,,7,8
#,,9,10,11
# -------------

#Z = np.genfromtxt("missing.dat", delimiter=",")
#Esta línea de código lee el archivo "missing.dat" utilizando np.genfromtxt(). 
#np.genfromtxt() intenta inferir el tipo de dato de cada columna en función de los valores que encuentra. Si encuentra valores que no son numéricos, 
#los considerará como valores faltantes o nan 

In [56]:
# 47. ¿Cuál es el equivalente de enumerate para los arrays de numpy
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [57]:
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [58]:
# 48. Generar un generico 2D a una distribución similar a una gaussiana
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [59]:
# 49. ¿Cómo colocar en lugares random elementos p en un array 2D?
n = 10
p = 3 # Número de elementos aleatorios a colocar
Z = np.zeros((n,n))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [60]:
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [61]:
# 50. Restar la media de cada fila de una matriz
X = np.random.rand(5, 10)
print(X)

[[0.766748   0.97045098 0.94447376 0.36121226 0.02899799 0.18031253
  0.0240412  0.13118498 0.30365295 0.59579258]
 [0.18437255 0.13433861 0.59127059 0.4833036  0.71578194 0.20931468
  0.07206728 0.13652178 0.21251986 0.17399219]
 [0.27916609 0.4354938  0.36189497 0.6016895  0.66432021 0.3537646
  0.32337577 0.43078843 0.63733461 0.47852956]
 [0.03671425 0.28003898 0.84839608 0.44404313 0.45601341 0.69481635
  0.93746651 0.58916455 0.6143005  0.79599887]
 [0.59728167 0.22308161 0.82603497 0.53771105 0.73701641 0.59103694
  0.80876767 0.39390651 0.38976505 0.63761902]]


In [62]:
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.33606128  0.53976425  0.51378704 -0.06947447 -0.40168873 -0.25037419
  -0.40664552 -0.29950174 -0.12703378  0.16510586]
 [-0.10697575 -0.15700969  0.29992228  0.1919553   0.42443363 -0.08203363
  -0.21928103 -0.15482653 -0.07882845 -0.11735612]
 [-0.17746966 -0.02114196 -0.09474079  0.14505374  0.20768446 -0.10287116
  -0.13325998 -0.02584732  0.18069885  0.02189381]
 [-0.53298101 -0.28965628  0.27870082 -0.12565213 -0.11368186  0.12512109
   0.36777125  0.01946928  0.04460524  0.2263036 ]
 [ 0.02305958 -0.35114048  0.25181288 -0.03651104  0.16279432  0.01681485
   0.23454558 -0.18031558 -0.18445704  0.06339693]]


In [63]:
# 51. ¿Cómo ordenar un array por la columna n-ésima?
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 9 1]
 [1 3 4]
 [9 4 9]]
[[1 3 4]
 [9 4 9]
 [9 9 1]]


In [64]:
# 52. ¿Cómo determinar si un array 2D dado tiene columnas nulas?
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())


False


In [65]:
# 53. Encontrar el valor más cercano dado un valor en un array
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5120764818023512


In [66]:
# 54. Crear una class tipo array que tenga que tenga un atributo de nombre
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

In [67]:
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [68]:
# 55. Considerar un vector dado, ¿cómo añadir un 1 a cada elemento indexado por un segundo vector, teniendo en cuenta índices repetidos?
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 7. 1. 1. 1. 5. 3. 4. 5. 2.]


In [69]:
# 56. ¿Cómo acumular elementos de un vector (X) en un array (F) basado en una lista de índices (I)?
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [70]:
# 57. Considerando una imagen con dimensiones (w, h, 3) donde cada píxel se representa con tres valores para los canales de color (rojo, verde y azul) y cada valor se almacena como un byte sin signo (dtype=ubyte). 
#Calcular el número de colores únicos presentes en la imagen
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))


[0 1]


In [71]:
# 58. Considerando un array de cuatro dimensiones, ¿cómo sumar sobre los dos últimos ejes
#a la vez
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[39 50 58 44]
 [67 54 74 77]
 [60 62 70 59]]


In [72]:
# 59. Considerando un arreglo unidimensional vector D, ¿cómo calcular las medias de los subconjuntos de un vector 
# utilizando un vector S del mismo tamaño que describe los índices de los subconjuntos?
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.43611293 0.43244351 0.72012198 0.56201533 0.47459119 0.57877275
 0.41516364 0.34001592 0.59938413 0.43548817]


In [73]:
# 60. ¿Cómo obtener la diagonal de un producto punto?
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [74]:
C = np.dot(A, B)
diagonal = np.diag(C)
diagonal

array([30, 69, 90])

In [75]:
# 61. Considerando el vector [1,2,3,4,5]  cómo construir un nuevo vector a partir de un vector dado, 
#donde se intercalan tres ceros consecutivos entre cada valor del vector dado?
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [76]:
# 62. Considerando un array de dimension n (5,5,3), ¿Cómo multiplicarlo por un array dimensiones (5,5)
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [77]:
# 63. ¿Cómo intercambiar dos filas de una matriz?
A = np.arange(25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [79]:
#64. Considerar un set de 10 triplets que describen 10 triangulos (con vertices compartidos)
#Encontrar en el set la unica linea de segmentos que compone todo el triangulo
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 10) ( 2, 24) ( 2, 32) ( 2, 75) ( 5, 22) ( 5, 26) ( 5, 70) ( 5, 94)
 (10, 24) (17, 32) (17, 35) (21, 53) (21, 98) (22, 94) (26, 70) (32, 35)
 (32, 75) (34, 84) (34, 99) (36, 53) (36, 57) (52, 68) (52, 81) (53, 57)
 (53, 98) (68, 81) (77, 78) (77, 87) (78, 87) (84, 99)]


In [80]:
# 65. ¿Cómo generar un array A a partir de un array C que representa un conteo de ocurrencias (bincount)?
C = np.bincount([1,1,2,3,4,4,6])
C

array([0, 2, 1, 1, 2, 0, 1], dtype=int64)

In [81]:
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 3, 4, 4, 6])

In [82]:
# 66. ¿Cómo calcular promedios utilizando una un sliding window  sobre un array?
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [83]:
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [84]:
#67. ¿Cómo construir una matriz bidimensional a partir de un array unidimensional Z, donde la primera fila de la matriz es (Z[0], Z[1], Z[2]) 
#y cada fila subsiguiente está desplazada en 1 posición hacia la derecha, siendo la última fila (Z[-3], Z[-2], Z[-1])?
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

In [85]:
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [86]:
#68.¿Cómo negar un booleano, o cambiar de signo a un flotante no colocado?
Z_bool = np.random.randint(0,2,100)
print(Z_bool)
Z_bool_negado = np.logical_not(Z_bool)
print(Z_bool_negado)

[1 0 1 0 1 0 1 1 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1
 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 1 1 1 0 1 1 1 0 0 1 0 1 0 0 0 0 1
 0 1 1 1 1 0 1 0 0 1 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 0]
[False  True False  True False  True False False False  True False False
  True  True  True  True  True  True False False  True  True  True False
  True False  True False False  True  True  True False  True  True  True
 False  True  True  True  True False  True False  True  True False  True
  True False  True  True  True False  True  True  True False False False
  True False False False  True  True False  True False  True  True  True
  True False  True False False False False  True False  True  True False
 False  True  True False  True  True False  True False False False  True
 False  True False  True]


In [87]:
Z_float = np.random.uniform(-1.0, 1.0, 100)
print(Z_float)
Z_float_cambiado_signo = np.negative(Z_float)
print(Z_float_cambiado_signo)

[-3.79838201e-01  9.81095336e-02  9.49155731e-01  7.18950491e-01
  7.85941025e-02  5.15811938e-01 -5.08327303e-01 -3.12345760e-01
 -2.50842075e-02 -4.92011709e-01  5.54314512e-01  5.07361939e-01
 -7.68143077e-02  9.37222278e-01 -7.55374369e-01  6.63648657e-01
  8.92439901e-01  7.10690555e-01  4.48828424e-01  6.07797567e-01
  5.25905288e-01 -7.72514384e-01  9.54544253e-01  3.57140722e-01
 -2.84151698e-01 -1.96454838e-01 -9.30686979e-01  6.97980978e-01
  3.24437976e-01 -8.45531578e-01 -7.75493961e-01 -7.64718737e-01
 -9.58124275e-01 -1.94690519e-01  1.38193289e-01  4.45540460e-01
 -6.86711890e-01 -4.26302905e-02 -5.88183263e-01 -3.99417631e-01
  9.40702607e-02 -7.29861720e-01 -5.97495176e-01  2.30218108e-01
 -4.55172988e-01  8.29740674e-01  4.69147021e-01  6.47404096e-01
  7.10232418e-01  9.93933500e-01  5.21899560e-01 -3.35690338e-01
 -9.39172586e-02  9.66044890e-01 -6.26004999e-01 -2.28885590e-06
  8.94615260e-01  1.02711655e-01 -7.56253634e-01 -2.38757548e-01
  3.65434688e-01  6.78876

In [88]:
# 69. Considerando de 2  sets de puntos P0, P1 describiendo lineas (2d) y un punto p
#¿cómo calcular la distancia desde un punto p hasta cada línea definida por un par de puntos P0[i] y P1[i]?.
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[1.30124683 0.75273986 7.40497612 7.90396149 5.45257378 0.74837196
 3.53703903 1.58934633 8.15171173 8.54041444]


In [89]:
#70. Considerar un array arbitrario, escribir una función que extraiga una subparte con una forma fija y centrada en un elemento dado 
#(rellenando con un valor de relleno cuando sea necesario).
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)

def extraer_subparte(Z, forma, relleno, posicion):
 
    # Crear un array para la subparte con el valor de relleno especificado
    R = np.ones(forma, dtype=Z.dtype) * relleno
    
    # Convertir la posición a un array de enteros
    P = np.array(posicion).astype(int)
    
    # Obtener las formas de los arrays R y Z
    Rs = np.array(list(R.shape)).astype(int)
    Zs = np.array(list(Z.shape)).astype(int)
    
    # Calcular los índices de inicio y fin para la subparte en los arrays R y Z
    R_inicio = np.zeros((len(forma),)).astype(int)
    R_fin = np.array(list(forma)).astype(int)
    Z_inicio = (P - Rs // 2)
    Z_fin = (P + Rs // 2) + Rs % 2
    
    R_inicio = (R_inicio - np.minimum(Z_inicio, 0)).tolist()
    Z_inicio = (np.maximum(Z_inicio, 0)).tolist()
    R_fin = np.maximum(R_inicio, (R_fin - np.maximum(Z_fin - Zs, 0))).tolist()
    Z_fin = (np.minimum(Z_fin, Zs)).tolist()
    
    # Utilizar slicing para seleccionar la subparte del array original y copiarla en el array R
    r = [slice(inicio, fin) for inicio, fin in zip(R_inicio, R_fin)]
    z = [slice(inicio, fin) for inicio, fin in zip(Z_inicio, Z_fin)]
    R[r] = Z[z]
    
    return R


In [90]:
# Extraer la subparte
R = extraer_subparte(Z, shape, fill, position)
##ME DA ERROR !!!!!

TypeError: 'list' object is not callable

In [96]:
#72. Considerar un array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], ¿Cómo generar un array y R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
Z = np.arange(1,15,dtype=uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [98]:
#73. Calcular el rango de una matriz
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
rank

10

In [99]:
#74. ¿Cómo encontrar el valor más frecuente en un array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


In [100]:
#75. Extraer todos los bloques contiguos de 3x3 de una matriz random de 10x10
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 0 4]
   [0 3 1]
   [2 4 4]]

  [[0 4 0]
   [3 1 4]
   [4 4 0]]

  [[4 0 2]
   [1 4 1]
   [4 0 0]]

  [[0 2 0]
   [4 1 0]
   [0 0 4]]

  [[2 0 3]
   [1 0 2]
   [0 4 3]]

  [[0 3 0]
   [0 2 3]
   [4 3 4]]

  [[3 0 3]
   [2 3 1]
   [3 4 0]]

  [[0 3 4]
   [3 1 2]
   [4 0 1]]]


 [[[0 3 1]
   [2 4 4]
   [0 1 1]]

  [[3 1 4]
   [4 4 0]
   [1 1 0]]

  [[1 4 1]
   [4 0 0]
   [1 0 3]]

  [[4 1 0]
   [0 0 4]
   [0 3 0]]

  [[1 0 2]
   [0 4 3]
   [3 0 3]]

  [[0 2 3]
   [4 3 4]
   [0 3 3]]

  [[2 3 1]
   [3 4 0]
   [3 3 3]]

  [[3 1 2]
   [4 0 1]
   [3 3 4]]]


 [[[2 4 4]
   [0 1 1]
   [3 0 2]]

  [[4 4 0]
   [1 1 0]
   [0 2 4]]

  [[4 0 0]
   [1 0 3]
   [2 4 1]]

  [[0 0 4]
   [0 3 0]
   [4 1 3]]

  [[0 4 3]
   [3 0 3]
   [1 3 3]]

  [[4 3 4]
   [0 3 3]
   [3 3 3]]

  [[3 4 0]
   [3 3 3]
   [3 3 2]]

  [[4 0 1]
   [3 3 4]
   [3 2 1]]]


 [[[0 1 1]
   [3 0 2]
   [4 2 2]]

  [[1 1 0]
   [0 2 4]
   [2 2 0]]

  [[1 0 3]
   [2 4 1]
   [2 0 2]]

  [[0 3 0]
   [4 1 3]
   [0 2 0]]

  [[3 0 3]
   

In [104]:
# 76. Crear una subclase array 2D que Z[i,j] == Z[j,i]
class Symmetric(np.ndarray):
    def __setitem__(self, idx, value):
        i, j = idx
        super(Symmetric, self).__setitem__((i,j), value)
        super(Symmetric, self).__setitem__((j,i), value)
        
def symmetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symmetric)

S = symmetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1  8  9  7  5]
 [ 8  4 16 11  8]
 [ 9 16  5 42 12]
 [ 7 11 42  5 10]
 [ 5  8 12 10  7]]


In [105]:
#77. Considera un conjunto de p matrices con forma (n, n) y un conjunto de p vectores con forma (n, 1). 
#¿Cómo calcular la suma de los productos de las p matrices de una vez? (el resultado tiene forma (n, 1))
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)
# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [108]:
#78. Dado un arreglo de 16x16, ¿cómo obtener la suma de bloques (tamaño del bloque es 4x4)?
Z = np.ones((16, 16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                    np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

In [111]:
#79. ¿Cómo implementar el Juego de la vida usando arrays de numpy?
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
    Z[1:-1,0:-2] + Z[1:-1,2:] +
    Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])
    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
Z

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [112]:
# 80. ¿Cómo obtener los n valores más grandes un array?
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

In [113]:
# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [114]:
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9998 9997 9996 9995]


In [115]:
#81. Dado un número arbitrario de vectores, construye el producto cartesiano (todas las combinaciones de cada elemento)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
    
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [118]:
#82. ¿Cómo crear un arreglo de registros a partir de un arreglo regular?
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
Z

array([['Hello', '2.5', '3'],
       ['World', '3.6', '2']], dtype='<U32')

In [119]:
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
R

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

In [124]:
#83. Considera un vector grande Z, calcula Z elevado a la potencia 3 usando 3 métodos diferentes.
x = np.random.rand(int(5e7))
np.power(x,3)


array([0.84957275, 0.00251297, 0.64848055, ..., 0.06285752, 0.42857821,
       0.02223169])

In [125]:
x*x*x

array([0.84957275, 0.00251297, 0.64848055, ..., 0.06285752, 0.42857821,
       0.02223169])

In [126]:
 np.einsum('i,i,i->i',x,x,x)

array([0.84957275, 0.00251297, 0.64848055, ..., 0.06285752, 0.42857821,
       0.02223169])

In [129]:
#84. "Dados dos arreglos A y B de forma (8,3) y (2,2) respectivamente. ¿Cómo encontrar las filas de A que contienen elementos de cada fila de B, 
#independientemente del orden de los elementos en B?
A = np.random.randint(0,5,(8,3))
print(A)
print('----------')
B = np.random.randint(0,5,(2,2))
print(B)
print('----------')
C = (A[..., np.newaxis, np.newaxis] == B)
print(C)
print('----------')
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[[3 1 1]
 [3 0 2]
 [0 4 2]
 [0 1 0]
 [3 3 1]
 [1 0 3]
 [3 4 3]
 [4 0 1]]
----------
[[4 0]
 [0 1]]
----------
[[[[False False]
   [False False]]

  [[False False]
   [False  True]]

  [[False False]
   [False  True]]]


 [[[False False]
   [False False]]

  [[False  True]
   [ True False]]

  [[False False]
   [False False]]]


 [[[False  True]
   [ True False]]

  [[ True False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False  True]
   [ True False]]

  [[False False]
   [False  True]]

  [[False  True]
   [ True False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False  True]]]


 [[[False False]
   [False  True]]

  [[False  True]
   [ True False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[ True False]
   [False False]]

  [[False False]
   [False False]]]


 [[[ True False]
   [False False]]

  [[False  True]
   [ True False]]

  [[False False]
   [False  True]]]]
----------


In [130]:
#85. Dada una matriz de 10x3, extrae las filas con valores desiguales (por ejemplo, [2,2,3])
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[4 2 0]
 [0 1 4]
 [3 4 1]
 [2 4 3]
 [1 3 1]
 [2 2 1]
 [4 4 1]
 [2 2 4]
 [0 3 3]
 [2 0 4]]
[[4 2 0]
 [0 1 4]
 [3 4 1]
 [2 4 3]
 [1 3 1]
 [2 2 1]
 [4 4 1]
 [2 2 4]
 [0 3 3]
 [2 0 4]]


In [131]:
#86. Convierte un vector de enteros en una representación binaria de matriz.
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [132]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [133]:
#87. Dada una matriz bidimensional, ¿cómo extraer filas únicas?
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 1]]


In [135]:
#88. Considerando 2 vectores A y B, escribe el equivalente de einsum para las funciones inner, outer, sum y mul.
np.einsum('i->', A)  # np.sum(A)
np.einsum('i,i->i', A, B)  # A * B
np.einsum('i,i', A, B)  # np.inner(A, B)
np.einsum('i,j', A, B)  # np.outer(A, B)

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

In [136]:
#Error !!!!!!!

In [138]:
#89. Dada una trayectoria descrita por dos vectores (X, Y), ¿cómo muestrearla utilizando muestras equidistantes?
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x) # integrate path
y_int = np.interp(r_int, r, y)

In [139]:
r_int

array([  0.        ,   2.48788858,   4.97577716,   7.46366574,
         9.95155432,  12.43944289,  14.92733147,  17.41522005,
        19.90310863,  22.39099721,  24.87888579,  27.36677437,
        29.85466295,  32.34255152,  34.8304401 ,  37.31832868,
        39.80621726,  42.29410584,  44.78199442,  47.269883  ,
        49.75777158,  52.24566016,  54.73354873,  57.22143731,
        59.70932589,  62.19721447,  64.68510305,  67.17299163,
        69.66088021,  72.14876879,  74.63665736,  77.12454594,
        79.61243452,  82.1003231 ,  84.58821168,  87.07610026,
        89.56398884,  92.05187742,  94.539766  ,  97.02765457,
        99.51554315, 102.00343173, 104.49132031, 106.97920889,
       109.46709747, 111.95498605, 114.44287463, 116.9307632 ,
       119.41865178, 121.90654036, 124.39442894, 126.88231752,
       129.3702061 , 131.85809468, 134.34598326, 136.83387184,
       139.32176041, 141.80964899, 144.29753757, 146.78542615,
       149.27331473, 151.76120331, 154.24909189, 156.73

In [140]:
x_int

array([ 0.00000000e+00, -3.73131229e-01, -2.59817608e+00, -3.26212050e+00,
       -2.18442687e+00, -2.98929946e-02,  2.42923642e+00,  4.54913599e+00,
        5.92318348e+00,  6.35117933e+00,  5.82369277e+00,  4.46259540e+00,
        2.47320794e+00,  1.09577220e-01, -2.36575300e+00, -4.71261671e+00,
       -6.72701769e+00, -8.25541575e+00, -9.18486120e+00, -9.46381505e+00,
       -9.11085788e+00, -8.12875279e+00, -6.63306046e+00, -4.69271059e+00,
       -2.44736165e+00, -2.05444585e-02,  2.46101146e+00,  4.86841760e+00,
        7.08937968e+00,  9.02539126e+00,  1.05948609e+01,  1.17357250e+01,
        1.24068974e+01,  1.25885805e+01,  1.22815267e+01,  1.15053927e+01,
        1.02963689e+01,  8.70429550e+00,  6.78948686e+00,  4.61716636e+00,
        2.25853448e+00, -1.98731680e-01, -2.68040566e+00, -5.11543300e+00,
       -7.41973991e+00, -9.53891040e+00, -1.14237629e+01, -1.29919305e+01,
       -1.42355069e+01, -1.51243232e+01, -1.56061571e+01, -1.57219415e+01,
       -1.54217066e+01, -

In [141]:
y_int

array([ 0.00000000e+00,  1.74026724e+00,  9.81816584e-01, -1.34251287e+00,
       -3.53191891e+00, -4.70449474e+00, -4.59573427e+00, -3.33831870e+00,
       -1.28956083e+00,  1.14234685e+00,  3.55645601e+00,  5.62188218e+00,
        7.09389488e+00,  7.82951803e+00,  7.78700678e+00,  6.99685666e+00,
        5.55535240e+00,  3.60417006e+00,  1.30506373e+00, -1.15819722e+00,
       -3.61328132e+00, -5.89130465e+00, -7.87065053e+00, -9.41689057e+00,
       -1.04714836e+01, -1.09903787e+01, -1.09354306e+01, -1.03330912e+01,
       -9.22690166e+00, -7.67489830e+00, -5.75257980e+00, -3.54832201e+00,
       -1.15854355e+00,  1.31709956e+00,  3.78023622e+00,  6.13780326e+00,
        8.30540149e+00,  1.02098724e+01,  1.17910419e+01,  1.29972950e+01,
        1.37774249e+01,  1.41319792e+01,  1.40585758e+01,  1.35636816e+01,
        1.26345244e+01,  1.13409083e+01,  9.72216360e+00,  7.79464305e+00,
        5.64544223e+00,  3.32503222e+00,  8.88107041e-01, -1.59329248e+00,
       -4.05992507e+00, -

In [143]:
#90. Dado un entero n y un arreglo 2D X, selecciona de X las filas que pueden interpretarse como extracciones de una distribución multinomial con n grados, es decir, las filas que contienen solo enteros
#y cuya suma sea n.
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]
